### ISSUE TITLE
Styling Fetch Responses. 

### ISSUE THREAD

**Issue by wevexOP** [jxmesin/Spoopy_App#23]
Now that we have configured the API's and got them both to show the responses on the html page. We need to add styling to them.

[ ] Add Cool Font 

[ ] Correct the sizing 

[ ] Make sure the flex-box properties are set and fluid to the view port.

**Comment by Magerick** [comment]
[X] Cool Font

[?] Correct the sizing? I guess, if you count the font sizes.

[ ] Flex properties.
